"use client";

import { useState, useEffect, useContext, useRef } from "react";
import { Sale, SaleItem, Product } from "@/lib/types";
import {
  getApiErrorText,
  parseFormError,
  extractApiErrorFields,
} from "@/lib/errorParsers";
import { useCredit, type Customer } from "@/hooks/useCredit";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Spinner } from "@/components/ui/spinner";
import { X, Plus, Trash2, Printer } from "lucide-react";
import { useSettings } from "@/context/SettingsContext";
import { useAuth } from "@/context/AuthContext";
import { useData } from "@/context/DataContext";
import { ThemeContext } from "@/components/theme-provider";
import { v4 as uuidv4 } from "uuid";
import Select from "react-select";
import { printService } from "@/lib/printService";
import { useToast } from "@/components/ui/use-toast";
import { ReceiptTemplate } from "./ReceiptTemplate";
import { downloadReceiptPdf } from "@/lib/pdfUtils";
import {
  getCurrentCreditSaleTxnId,
  getNextCreditSaleTxnId,
} from "@/lib/transactionIdStorage";
// import { Printer } from "lucide-react";

interface SalesFormProps {
  products: Product[];
  onSubmit: (sale: Sale) => Promise<void> | void;
  onCancel: () => void;
  currentUserId: string;
  currentUsername: string;
  sale?: Sale; // Optional: if provided, form is in edit mode
  RecieptPreview?: (sale: Sale) => Promise<void> | void; // Optional: list of items already sold (for editing)
  serverError?: string;
}

export function SalesForm({
  products,
  onSubmit,
  onCancel,
  currentUserId,
  currentUsername: _currentUsername,
  sale,
  RecieptPreview,
  serverError = "",
}: SalesFormProps) {
  const { formatCurrency } = useSettings();
  const { user, business } = useAuth();
  const { theme } = useContext(ThemeContext) || { theme: "light" };
  const { customers, fetchCustomers } = useCredit();
  const { sales } = useData();

  const isWholesaler = business?.businessType === "wholesaler";
  const allowCreditSales = isWholesaler || Boolean(sale?.isCreditSale);
  const isEditing = !!sale; // Determine if we're in edit mode

  const [items, setItems] = useState<SaleItem[]>(
    sale?.items?.map((item) => ({
      ...item,
    })) || [],
  );
  const [selectedProductId, setSelectedProductId] = useState("");
  const [quantity, setQuantity] = useState("");
  const [customerName, setCustomerName] = useState(sale?.customerName || "");
  const [customerId, setCustomerId] = useState(sale?.customerId || "");
  const [isCreditSale, setIsCreditSale] = useState(sale?.isCreditSale || false);
  const [paymentType, setPaymentType] = useState(sale?.paymentType || "cash");
  const [txnId, setTxnId] = useState(sale?.txnId || "");
  const [dueDate, setDueDate] = useState(sale?.dueDate || "");
  const [hasAutoGeneratedTxnId, setHasAutoGeneratedTxnId] = useState(false);
  const isCreditSaleActive =
    allowCreditSales && (isCreditSale || paymentType === "credit");
  const [saleDate, setSaleDate] = useState(
    sale?.date || new Date().toISOString().split("T")[0],
  );
  const [notes, setNotes] = useState(sale?.notes || "");

  // Check if selected customer has outstanding credit debt
  const customerHasOutstandingDebt = customerId
    ? sales.some(
        (s) =>
          (s.customerId === customerId || s._id === customerId) &&
          s.isCreditSale &&
          ["pending", "pending_approval", "partial"].includes(
            s.paymentStatus || "",
          ),
      )
    : false;

  useEffect(() => {
    if (!sale && isCreditSaleActive && !hasAutoGeneratedTxnId && !txnId) {
      const generatedTxnId = getCurrentCreditSaleTxnId();
      setTxnId(generatedTxnId);
      setHasAutoGeneratedTxnId(true);
    }
  }, [sale, isCreditSaleActive, hasAutoGeneratedTxnId, txnId]);

  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleTxnIdChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const nextValue = e.target.value;
    setHasAutoGeneratedTxnId(false);
    if (isCreditSaleActive) {
      setTxnId(nextValue.replace(/\D/g, "").slice(0, 5));
      return;
    }

    setTxnId(nextValue);
  };

  // Load credit customers for wholesaler business use
  useEffect(() => {
    if (isWholesaler) {
      void fetchCustomers();
    }
  }, [isWholesaler, fetchCustomers]);

  // Update form state when sale prop changes
  useEffect(() => {
    if (sale) {
      setItems(sale.items || []);
      setCustomerName(sale.customerName || "");
      setCustomerId(sale.customerId || "");
      setIsCreditSale(Boolean(sale.isCreditSale));
      setPaymentType(sale.paymentType || "cash");
      setTxnId(sale.txnId || "");
      setDueDate(sale.dueDate || "");
      setSaleDate(sale.date || new Date().toISOString().split("T")[0]);
      setNotes(sale.notes || "");
      setSelectedProductId("");
      setQuantity("");
      setErrors({});
    }
  }, [sale]);

  // Update general error when serverError prop changes
  useEffect(() => {
    if (serverError) {
      setErrors((prev) => ({
        ...prev,
        general: serverError,
      }));
    }
  }, [serverError]);

  // Clear general error when form data changes (allow user to retry)
  useEffect(() => {
    if (errors.general && !serverError) {
      const { general: _general, ...rest } = errors;
      void _general;
      setErrors(rest);
    }
  }, [
    customerName,
    paymentType,
    txnId,
    saleDate,
    notes,
    items,
    selectedProductId,
    quantity,
  ]);

  const productOptions = products
    ?.filter((p) => {
      const hasStock = p.currentStock > 0;
      if (!hasStock) {
      }
      return hasStock;
    })
    .map((p) => ({
      value: p._id || p.id,
      label: `${p.name} (${p.currentStock} available)`,
    }));

  const customerOptions = customers.map((customer) => {
    const customerLimit = Number(customer.creditLimit ?? 0);
    const outstandingBalance = Number(customer.outstandingBalance ?? 0);
    const hasReachedLimit = outstandingBalance >= customerLimit;

    return {
      value: customer._id || customer.id || "",
      label: customer.name,
      data: customer,
      isDisabled: hasReachedLimit,
    };
  });

  const addItem = () => {
    if (!selectedProductId || !quantity) {
      setErrors({ product: "Select product and quantity" });
      return;
    }

    let product = products.find(
      (p) => p.id === selectedProductId || p._id === selectedProductId,
    );

    // Fallback: if not found by ID, try alternate identifiers
    if (!product) {
      product = products.find(
        (p) => p.id === selectedProductId || p._id === selectedProductId,
      );
    }

    if (!product) {
      setErrors({ product: "Product not found. Please select again." });
      return;
    }

    if (parseInt(quantity) > product.currentStock) {
      setErrors({ quantity: `Only ${product.currentStock} available` });
      return;
    }

    const saleItem: SaleItem = {
      productId: product.id || product._id || selectedProductId,
      quantity: parseInt(quantity),
      unitPrice: product.unitPrice,
      total: parseInt(quantity) * product.unitPrice,
    };

    setItems([...items, saleItem]);
    setSelectedProductId("");
    setQuantity("");
    setErrors({});
  };

  const removeItem = (index: number) => {
    setItems(items.filter((_, i) => i !== index));
  };

  const totalAmount = items.reduce((sum, item) => sum + item.total, 0);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const newErrors: Record<string, string> = {};
    if (items.length === 0)
      newErrors.items = "Add at least one item to the sale";
    if (isCreditSale && !customerId)
      newErrors.customerId = "Please select a customer for credit sales";
    if (!customerName.trim())
      newErrors.customerName = "Customer name is required";
    if (paymentType !== "cash" && !txnId.trim())
      newErrors.txnId = "Transaction ID is required";
    if (isCreditSale && !dueDate)
      newErrors.dueDate = "Due date is required for credit sales";

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    setIsSubmitting(true);
    setErrors({});

    try {
      // If editing, use the existing saleNumber and ID; otherwise generate new ones
      const saleNumber = isEditing ? sale.saleNumber : "";
      const newTxnId =
        !isEditing && isCreditSaleActive && hasAutoGeneratedTxnId
          ? getNextCreditSaleTxnId()
          : txnId || uuidv4();

      const saleData: Sale = {
        ...(isEditing && { _id: sale._id }),
        saleNumber,
        date: saleDate,
        items: items.map((item) => ({
          ...item,
        })),
        totalAmount,
        status: "completed",
        notes,
        createdBy: currentUserId,
        customerId: customerId || undefined,
        customerName,
        isCreditSale: isCreditSaleActive,
        paymentType,
        paymentStatus: isCreditSaleActive ? "pending" : "paid",
        paidAmount: isCreditSaleActive ? 0 : totalAmount,
        txnId: newTxnId,
        dueDate: isCreditSaleActive ? dueDate : undefined,
        createdAt: isEditing ? sale.createdAt : new Date().toISOString(),
        ...(isEditing && { _id: sale._id }),
      };

      // Submit the sale
      await onSubmit(saleData);

      // Create receipt payload with products data for display
      const receiptPayload = {
        ...saleData,
        products, // Include products so receipt can look up product names
      };

      // Call receipt preview with complete data
      RecieptPreview?.(receiptPayload);

      // Clear form only after a successful submission
      setItems([]);
      setCustomerName("");
      setPaymentType("cash");
      setTxnId("");
      setIsCreditSale(false);
      setHasAutoGeneratedTxnId(false);
      setSaleDate(new Date().toISOString().split("T")[0]);
      setNotes("");
      setErrors({});
    } catch (error) {
      console.error("Failed to complete sale:", error);
      const errorText = getApiErrorText(error);
      const serverErrors = extractApiErrorFields(error);
      const parsedErrors =
        Object.keys(serverErrors).length > 0
          ? serverErrors
          : parseFormError(errorText);

      if (Object.keys(parsedErrors).length > 0) {
        setErrors({
          ...parsedErrors,
          general:
            errorText ||
            `Failed to ${isEditing ? "update" : "complete"} sale. Please try again.`,
        });
      } else {
        setErrors({
          general:
            errorText ||
            `Failed to ${isEditing ? "update" : "complete"} sale. Please try again.`,
        });
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4 ">
      {errors.general && (
        <div className="flex items-center gap-2 p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
          <X className="w-4 h-4 shrink-0" />
          <span>{errors.general}</span>
        </div>
      )}

      {isEditing && (
        <div className="p-3 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-700 rounded-lg">
          <p className="text-sm font-medium text-blue-900 dark:text-blue-100">
            Sale Number:{" "}
            <span className="font-mono font-bold">{sale.saleNumber}</span>
          </p>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-slate-200 mb-1">
            Customer Name *
          </label>
          <Input
            disabled={user?.role === "accountant"}
            value={customerName}
            onChange={(e) => setCustomerName(e.target.value)}
            placeholder="Enter customer name"
            className={`border-2 dark:bg-slate-900 dark:text-slate-100 disabled:opacity-50 disabled:cursor-not-allowed ${
              errors.customerName
                ? "border-red-500 dark:border-red-500"
                : "border-teal-200 dark:border-teal-700"
            }`}
          />
          {errors.customerName && (
            <div className="flex items-center gap-2 mt-1">
              <span className="text-xs text-red-500">
                {errors.customerName}
              </span>
            </div>
          )}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-slate-200 mb-1">
            Date of Sale *
          </label>
          <Input
            disabled={user?.role === "accountant"}
            type="date"
            value={saleDate}
            onChange={(e) => setSaleDate(e.target.value)}
            className="border-2  border-teal-200 dark:border-teal-700 dark:bg-slate-900 dark:text-slate-100 disabled:opacity-50 disabled:cursor-not-allowed"
          />
        </div>

        {business?.businessType !== "retail" && (
          <div className="md:col-span-2">
            <div className="flex flex-col gap-2">
              <div className="flex flex-col gap-2">
                <div className="flex items-center gap-2">
                  <input
                    id="creditSale"
                    type="checkbox"
                    checked={isCreditSale}
                    disabled={
                      !allowCreditSales ||
                      user?.role === "accountant" ||
                      customerHasOutstandingDebt
                    }
                    onChange={(e) => {
                      const checked = e.target.checked;
                      setIsCreditSale(checked);
                      if (checked) {
                        setPaymentType("credit");
                      } else if (paymentType === "credit") {
                        setPaymentType("cash");
                      }
                    }}
                    className="h-4 w-4 text-teal-600 border-gray-300 rounded focus:ring-teal-500"
                  />
                  <label
                    htmlFor="creditSale"
                    className="text-sm font-medium text-gray-700 dark:text-slate-200"
                  >
                    Record as credit sale
                  </label>
                </div>
                {!isWholesaler && !sale?.isCreditSale && (
                  <p className="text-xs text-slate-500 dark:text-slate-400">
                    Credit sales are available for wholesaler businesses only.
                  </p>
                )}
                {customerHasOutstandingDebt && (
                  <p className="text-xs text-red-600 dark:text-red-400">
                    This customer has an outstanding credit sale. Please settle
                    the existing balance before creating a new credit sale.
                  </p>
                )}
              </div>

              {isCreditSaleActive && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-slate-200 mb-1">
                      Credit Customer *
                    </label>
                    <Select
                      className="w-full dark:text-slate-100"
                      classNamePrefix="react-select"
                      value={customerOptions.find(
                        (option) => option.value === customerId,
                      )}
                      onChange={(selectedOption) => {
                        const value = selectedOption?.value || "";
                        setCustomerId(value);
                        const selected = customers.find(
                          (customer) =>
                            customer.id === value || customer._id === value,
                        );
                        if (selected) {
                          setCustomerName(selected.name);
                        }
                      }}
                      options={customerOptions}
                      placeholder="Select a customer..."
                      isDisabled={user?.role === "accountant"}
                      isOptionDisabled={(option) => Boolean(option.isDisabled)}
                      formatOptionLabel={(option) => {
                        const customer = option.data as Customer | undefined;
                        if (!customer) {
                          return <span>{option.label}</span>;
                        }

                        const creditLimit = Number(customer.creditLimit ?? 0);

                        return (
                          <div className="flex items-center justify-between gap-2">
                            <span className="truncate">{customer.name}</span>
                            <span className="text-xs text-slate-500 dark:text-slate-400 shrink-0">
                              Limit: {formatCurrency(creditLimit)}
                            </span>
                          </div>
                        );
                      }}
                      styles={{
                        control: (provided, state) => ({
                          ...provided,
                          border: state.isFocused
                            ? "2px solid rgb(20 184 166)"
                            : `2px solid ${theme === "dark" ? "rgb(71 85 105)" : "rgb(165 243 252)"}`,
                          fontSize: "0.875rem",
                          backgroundColor:
                            theme === "dark" ? "rgb(30 41 59)" : "white",
                          color:
                            theme === "dark" ? "rgb(226 232 240)" : "inherit",
                          minHeight: "2.5rem",
                          boxShadow: state.isFocused
                            ? `0 0 0 3px ${theme === "dark" ? "rgba(20, 184, 166, 0.1)" : "rgba(20, 184, 166, 0.1)"}`
                            : "none",
                          padding: "0",
                          cursor:
                            user?.role === "accountant"
                              ? "not-allowed"
                              : "pointer",
                          opacity: user?.role === "accountant" ? 0.5 : 1,
                          transition:
                            "border-color 0.15s ease, box-shadow 0.15s ease",
                          "&:hover": {
                            borderColor: state.isFocused
                              ? "rgb(20 184 166)"
                              : `${theme === "dark" ? "rgb(71 85 105)" : "rgb(165 243 252)"}`,
                          },
                        }),
                        input: (provided) => ({
                          ...provided,
                          color:
                            theme === "dark" ? "rgb(226 232 240)" : "inherit",
                          padding: "2px 8px",
                        }),
                        singleValue: (provided) => ({
                          ...provided,
                          color:
                            theme === "dark" ? "rgb(226 232 240)" : "inherit",
                        }),
                        placeholder: (provided) => ({
                          ...provided,
                          color:
                            theme === "dark"
                              ? "rgb(148 163 184)"
                              : "rgb(107 114 128)",
                        }),
                        menu: (provided) => ({
                          ...provided,
                          backgroundColor:
                            theme === "dark" ? "rgb(30 41 59)" : "white",
                          border: `2px solid ${theme === "dark" ? "rgb(71 85 105)" : "rgb(165 243 252)"}`,
                          borderRadius: "0.5rem",
                          marginTop: "0.5rem",
                          boxShadow:
                            theme === "dark"
                              ? "0 4px 6px rgba(0, 0, 0, 0.3)"
                              : "0 4px 6px rgba(0, 0, 0, 0.1)",
                        }),
                        option: (provided, state) => ({
                          ...provided,
                          backgroundColor: state.isSelected
                            ? "rgb(20 184 166)"
                            : state.isFocused
                              ? theme === "dark"
                                ? "rgb(71 85 105)"
                                : "rgb(240 253 250)"
                              : theme === "dark"
                                ? "rgb(30 41 59)"
                                : "white",
                          color: state.isSelected
                            ? "#ffffff"
                            : theme === "dark"
                              ? "rgb(226 232 240)"
                              : "rgb(17 24 39)",
                          padding: "10px 12px",
                          cursor: state.isDisabled ? "not-allowed" : "pointer",
                          opacity: state.isDisabled ? 0.6 : 1,
                          fontWeight: state.isSelected ? "500" : "normal",
                          transition:
                            "background-color 0.1s ease, color 0.1s ease",
                          "&:active": {
                            backgroundColor: "rgb(13 148 136)",
                          },
                        }),
                      }}
                    />
                    {errors.customerId && (
                      <div className="flex items-center gap-2 mt-1">
                        <span className="text-xs text-red-500">
                          {errors.customerId}
                        </span>
                      </div>
                    )}
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-slate-200 mb-1">
                      Due Date *
                    </label>
                    <Input
                      disabled={user?.role === "accountant"}
                      type="date"
                      value={dueDate}
                      onChange={(e) => setDueDate(e.target.value)}
                      className={`border-2 dark:bg-slate-900 dark:text-slate-100 disabled:opacity-50 disabled:cursor-not-allowed ${
                        errors.dueDate
                          ? "border-red-500 dark:border-red-500"
                          : "border-teal-200 dark:border-teal-700"
                      }`}
                    />
                    {errors.dueDate && (
                      <div className="flex items-center gap-2 mt-1">
                        <span className="text-xs text-red-500">
                          {errors.dueDate}
                        </span>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-slate-200 mb-1">
            Payment Type *
          </label>
          <select
            disabled={user?.role === "accountant"}
            value={paymentType}
            onChange={(e) => {
              const value = e.target.value;
              setPaymentType(value);
              if (value === "credit") {
                setIsCreditSale(true);
              } else if (isCreditSale) {
                setIsCreditSale(false);
              }
            }}
            className="w-full px-4 py-2 border-2  border-teal-200 dark:border-teal-700 rounded-lg tex9-sm bg-white dark:bg-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-teal-500 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <option value="cash">Cash</option>
            <option value="card">Card</option>
            <option value="transfer">Bank Transfer</option>
            <option value="cheque">Cheque</option>
            {allowCreditSales && <option value="credit">Credit</option>}
            <option value="other">Other</option>
          </select>
        </div>

        {paymentType !== "cash" && (
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-slate-200 mb-1">
              Transaction ID *
            </label>
            <Input
              disabled={user?.role === "accountant"}
              value={txnId}
              onChange={handleTxnIdChange}
              placeholder={isCreditSaleActive ? "00001" : "e.g., TXN-123456"}
              maxLength={isCreditSaleActive ? 5 : undefined}
              inputMode={isCreditSaleActive ? "numeric" : "text"}
              className={`border-2  dark:bg-slate-800 dark:text-slate-100 disabled:opac9ty-50 disabled:cursor-not-allowed ${
                errors.txnId
                  ? "border-red-500 dark:border-red-500"
                  : "border-teal-200 dark:border-teal-700"
              }`}
            />
            {errors.txnId && (
              <div className="flex items-center gap-2 mt-1">
                <span className="text-xs text-red-500">{errors.txnId}</span>
              </div>
            )}
          </div>
        )}
      </div>

      <div className="space-y-2">
        <label className="block text-sm font-medium text-gray-700 dark:text-slate-300">
          Add Products
        </label>
        <p className="text-sm text-muted-foreground">
          (Click the "+ Add" button to include the product in the sale)
        </p>
        <div className="flex gap-2">
          <Select
            className="flex-1 dark:text-slate-100 dark:bg-slate-900 disabled:cursor-not-allowed"
            classNamePrefix="react-select"
            value={productOptions?.find(
              (option) => option.value === selectedProductId,
            )}
            onChange={(selectedOption) =>
              setSelectedProductId(selectedOption?.value || "")
            }
            options={productOptions}
            placeholder="Select product"
            isDisabled={user?.role === "accountant"}
            styles={{
              control: (provided, state) => ({
                ...provided,
                border: state.isFocused
                  ? "2px solid rgb(20 184 166)"
                  : `2px solid ${theme === "dark" ? "rgb(71 85 105)" : "rgb(165 243 252)"}`,

                fontSize: "0.875rem",
                backgroundColor: theme === "dark" ? "rgb(30 41 59)" : "white",
                color: theme === "dark" ? "rgb(226 232 240)" : "inherit",
                minHeight: "2.5rem",
                boxShadow: state.isFocused
                  ? `0 0 0 3px ${theme === "dark" ? "rgba(20, 184, 166, 0.1)" : "rgba(20, 184, 166, 0.1)"}`
                  : "none",
                padding: "0",
                cursor: user?.role === "accountant" ? "not-allowed" : "pointer",
                opacity: user?.role === "accountant" ? 0.5 : 1,
                transition: "border-color 0.15s ease, box-shadow 0.15s ease",
                "&:hover": {
                  borderColor: state.isFocused
                    ? "rgb(20 184 166)"
                    : `${theme === "dark" ? "rgb(71 85 105)" : "rgb(165 243 252)"}`,
                },
              }),
              input: (provided) => ({
                ...provided,
                color: theme === "dark" ? "rgb(226 232 240)" : "inherit",
                padding: "2px 8px",
              }),
              singleValue: (provided) => ({
                ...provided,
                color: theme === "dark" ? "rgb(226 232 240)" : "inherit",
              }),
              placeholder: (provided) => ({
                ...provided,
                color:
                  theme === "dark" ? "rgb(148 163 184)" : "rgb(107 114 128)",
              }),
              menu: (provided) => ({
                ...provided,
                backgroundColor: theme === "dark" ? "rgb(30 41 59)" : "white",
                border: `2px solid ${theme === "dark" ? "rgb(71 85 105)" : "rgb(165 243 252)"}`,
                borderRadius: "0.5rem",
                marginTop: "0.5rem",
                boxShadow:
                  theme === "dark"
                    ? "0 4px 6px rgba(0, 0, 0, 0.3)"
                    : "0 4px 6px rgba(0, 0, 0, 0.1)",
              }),
              option: (provided, state) => ({
                ...provided,
                backgroundColor: state.isSelected
                  ? "rgb(20 184 166)"
                  : state.isFocused
                    ? theme === "dark"
                      ? "rgb(71 85 105)"
                      : "rgb(240 253 250)"
                    : theme === "dark"
                      ? "rgb(30 41 59)"
                      : "white",
                color: state.isSelected
                  ? "#ffffff"
                  : theme === "dark"
                    ? "rgb(226 232 240)"
                    : "rgb(17 24 39)",
                padding: "10px 12px",
                cursor: "pointer",
                fontWeight: state.isSelected ? "500" : "normal",
                transition: "background-color 0.1s ease, color 0.1s ease",
                "&:active": {
                  backgroundColor: "rgb(13 148 136)",
                },
              }),
              indicatorSeparator: (provided) => ({
                ...provided,
                backgroundColor:
                  theme === "dark" ? "rgb(71 85 105)" : "rgb(229 231 235)",
              }),
              dropdownIndicator: (provided, _state) => ({
                ...provided,
                color:
                  theme === "dark" ? "rgb(148 163 184)" : "rgb(107 114 128)",
                transition: "color 0.15s ease",
                "&:hover": {
                  color: "rgb(20 184 166)",
                },
              }),
            }}
          />
          <Input
            disabled={user?.role === "accountant"}
            type="number"
            min="1"
            value={quantity}
            onChange={(e) => setQuantity(e.target.value)}
            placeholder="Qty"
            className="w-20 border-2  border-teal-200 dark:border-teal-700 dark:bg-slate-900 dark:text-slate-100 disabled:opacity-50 disabled:cursor-not-allowed"
          />
          <Button
            disabled={user?.role === "accountant"}
            type="button"
            onClick={addItem}
            className="bg-teal-600 hover:bg-teal-700 dark:bg-teal-600 dark:hover:bg-teal-700 gap-1 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Plus className="w-4 h-4" />
            Add
          </Button>
        </div>
        {errors.product && (
          <p className="text-red-500 text-xs">{errors.product}</p>
        )}
        {errors.quantity && (
          <p className="text-red-500 text-xs">{errors.quantity}</p>
        )}
      </div>

      {items.length > 0 && (
        <Card className="bg-gray-50 dark:bg-slate-800 border-teal-200 dark:border-teal-700">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm text-gray-900 dark:text-teal-100">
              Sale Items ({items.length})
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {items.map((item, index) => {
              const product = products.find(
                (p) => p.id === item.productId || p._id === item.productId,
              );
              return (
                <div
                  key={index}
                  className="flex items-center justify-between p-2 bg-white dark:bg-slate-800 rounded border border-gray-200 dark:border-teal-700"
                >
                  <div className="flex-1">
                    <p className="text-sm font-medium text-gray-900 dark:text-slate-100">
                      {product?.name}
                    </p>
                    <p className="text-xs text-gray-600 dark:text-slate-400">
                      {item.quantity} × {formatCurrency(item.unitPrice)} ={" "}
                      {formatCurrency(item.total)}
                    </p>
                  </div>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    onClick={() => removeItem(index)}
                    className="text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20"
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              );
            })}
            <div className="border-t border-gray-200 dark:border-teal-700 pt-2 mt-2">
              <p className="text-sm font-bold text-gray-900 dark:text-teal-100">
                Total: {formatCurrency(totalAmount)}
              </p>
            </div>
          </CardContent>
        </Card>
      )}

      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-slate-200 mb-1">
          Notes (Optional)
        </label>
        <textarea
          disabled={user?.role === "accountant"}
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          placeholder="Add any sale notes..."
          rows={3}
          className="w-full px-4 py-2 border-2 border-teal-200 dark:border-teal-700 rounded-lg text-sm bg-white dark:bg-slate-900 dark:text-slate-100 disabled:opacity-50 disabled:cursor-not-allowed"
        />
      </div>

      {errors.items && <p className="text-red-500 text-sm">{errors.items}</p>}

      <div className="flex gap-2 pt-4">
        <Button
          disabled={user?.role === "accountant" || isSubmitting}
          type="submit"
          className="bg-teal-600 hover:bg-teal-700 dark:bg-teal-600 dark:hover:bg-teal-700 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isSubmitting ? (
            <>
              <Spinner className="h-4 w-4" />
              {isEditing ? "Updating Sale..." : "Processing Sale..."}
            </>
          ) : isEditing ? (
            "Update Sale"
          ) : (
            "Complete Sale"
          )}
        </Button>
        <Button
          disabled={user?.role === "accountant" || isSubmitting}
          type="button"
          variant="outline"
          onClick={() => {
            setItems([]);
            setCustomerName("");
            setPaymentType("cash");
            setTxnId("");
            setSaleDate(new Date().toISOString().split("T")[0]);
            setNotes("");
            setErrors({});
            onCancel();
          }}
          className="dark:border-teal-700 dark:text-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Cancel
        </Button>
      </div>
    </form>
  );
}

// Immediate receipt for printing
export const RecieptPreview = ({
  payLoad,
}: {
  payLoad?: Sale & { products?: Product[] };
}) => {
  const receiptRef = useRef<HTMLDivElement>(null);
  const { toast } = useToast();
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  const handlePrintToPos = async () => {
    try {
      if (!printService.isQzAvailable()) {
        toast({
          title: "QZ Tray Not Available",
          description: "Please install QZ Tray to enable POS printing.",
          variant: "destructive",
        });
        return;
      }

      const connected = await printService.ensureConnected();
      if (!connected) {
        toast({
          title: "Connection Failed",
          description:
            "Could not connect to QZ Tray. Please check if it's running.",
          variant: "destructive",
        });
        return;
      }

      const items = (payLoad?.items || []) as SaleItem[];
      const totalAmount = items.reduce((sum, item) => sum + item.total, 0);

      const receiptData = {
        saleNumber: payLoad?.saleNumber || "---",
        date: payLoad?.date || new Date().toISOString(),
        customerName: payLoad?.customerName || "Walk-in",
        cashier: payLoad?.createdBy || "---",
        businessName: payLoad?.businessName,
        businessAddress: payLoad?.businessAddress,
        businessPhone: payLoad?.businessPhone?.contact,
        items: items.map((item) => {
          const product = payLoad?.products?.find(
            (p) => p.id === item.productId || p._id === item.productId,
          );
          return {
            name: product?.name || "Product",
            quantity: item.quantity,
            unitPrice: item.unitPrice,
            total: item.total,
          };
        }),
        totalAmount,
        paymentType: payLoad?.paymentType || "cash",
        txnId: payLoad?.txnId,
        notes: payLoad?.notes,
      };

      await printService.printReceipt(receiptData);

      toast({
        title: "Receipt Printed",
        description: "Receipt sent to POS printer successfully.",
      });
    } catch (error) {
      console.error("POS Print error:", error);
      toast({
        title: "Print Failed",
        description:
          error instanceof Error ? error.message : "Failed to print receipt.",
        variant: "destructive",
      });
    }
  };

  const handleDownloadPdf = async () => {
    if (!receiptRef.current) {
      toast({
        title: "Unable to generate PDF",
        description: "Receipt preview is not available.",
        variant: "destructive",
      });
      return;
    }
    setIsGeneratingPdf(true);
    try {
      const filename = `${payLoad?.saleNumber || "receipt"}-${new Date()
        .toISOString()
        .slice(0, 10)}.pdf`;

      const items = (payLoad?.items || []) as SaleItem[];
      const receiptItems = items.map((item) => {
        const product = payLoad?.products?.find(
          (p) => p.id === item.productId || p._id === item.productId,
        );
        return {
          name: product?.name || "Product",
          quantity: item.quantity,
          unitPrice: item.unitPrice,
          total: item.total,
        };
      });

      const receiptPayload = {
        businessName: payLoad?.businessName || "BUSINESS NAME",
        businessAddress: payLoad?.businessAddress || "Address Line 1",
        businessPhone:
          payLoad?.businessPhone?.contact || "Phone: XXXX-XXXX-XXXX",
        saleNumber: payLoad?.saleNumber || "---",
        date: payLoad?.date || new Date().toISOString(),
        cashier: payLoad?.createdBy || "---",
        customerName: payLoad?.customerName || "Walk-in",
        paymentMethod: payLoad?.paymentType || "cash",
        txnId: payLoad?.txnId,
        notes: payLoad?.notes,
        items: receiptItems,
      };

      const envBase =
        typeof process !== "undefined"
          ? process.env.NEXT_PUBLIC_API_BASE_URL
          : undefined;
      const serverBase = (envBase || "http://localhost:5000").replace(
        /\/$/,
        "",
      );
      const res = await fetch(`${serverBase}/pdf/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ receipt: receiptPayload, filename }),
        credentials: "include",
      });

      if (!res.ok) {
        const errText = await res.text().catch(() => "PDF generation failed");
        throw new Error(errText || "PDF generation failed");
      }

      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);

      toast({
        title: "Download Ready",
        description: "Your receipt PDF has been downloaded.",
      });
    } catch (error) {
      console.error("PDF export error:", error);
      toast({
        title: "Export Failed",
        description:
          error instanceof Error
            ? error.message
            : "Could not generate the receipt PDF.",
        variant: "destructive",
      });
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  return (
    <div className="space-y-4">
      <ReceiptTemplate payLoad={payLoad} receiptRef={receiptRef} />

      <div className="flex flex-wrap gap-2 justify-center no-print">
        <Button
          onClick={handlePrintToPos}
          disabled={!payLoad}
          className="bg-teal-600 hover:bg-teal-700 dark:bg-teal-600 dark:hover:bg-teal-700 gap-2"
        >
          <Printer className="w-4 h-4" />
          Print Receipt
        </Button>
        <Button
          onClick={handleDownloadPdf}
          disabled={!payLoad || isGeneratingPdf}
          className="bg-slate-900 hover:bg-slate-800 dark:bg-slate-900 dark:hover:bg-slate-800 gap-2"
        >
          {isGeneratingPdf ? "Generating PDF..." : "Download PDF"}
        </Button>
      </div>
    </div>
  );
};
